version: '2'
services:
    jhblog-app:
        image: jhblog
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhblog-mysql:3306/jhblog?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhblog-mysql:
        extends:
            file: mysql.yml
            service: jhblog-mysql
